
module.exports = {

    GET_DIAGNOSIS: 'GET_DIAGNOSIS',

    //Notification//
    ENQUEUE_SNACKBAR: 'ENQUEUE_SNACKBAR',
    CLOSE_SNACKBAR: 'CLOSE_SNACKBAR',
    REMOVE_SNACKBAR: 'REMOVE_SNACKBAR',


    //Auth Data//
    USER_LOGGED_IN: 'USER_LOGGED_IN',
    USER_LOGGED_OUT: 'USER_LOGGED_OUT',
    UPDATE_USER_DATA: 'UPDATE_USER_DATA',
    GET_TEAM_MEMBERS: 'GET_TEAM_MEMBERS',

    //Country//
    GET_COUNTRIES: "GET_COUNTRIES",
    GET_STATES: "GET_STATES",

    //Doctor//
    GET_DOCTORS: "GET_DOCTORS",
    GET_DOCTOR: "GET_DOCTOR",

    //Patient//
    SAVE_PATIENT: "SAVE_PATIENT",
    GET_PATIENT: "GET_PATIENT",


    //Labs and Imaging//
    GET_LAB_TESTS: "GET_LAB_TESTS",
    SAVE_LAB_ORDER: "SAVE_LAB_ORDER",
    SAVE_LAB_ENTRY: "SAVE_LAB_ENTRY",

    // FInd Rubrics//
    GET_SECTIONS: "GET_SECTIONS",
    GET_BODY_PARTS_BY_SECTION: "GET_BODY_PARTS_BY_SECTION",
    GET_SUB_SECTIONS_BY_BODY_PART: "GET_SUB_SECTIONS_BY_BODY_PART",
    SEARCH_SUB_SECTIONS: "SEARCH_SUB_SECTIONS",
    ADD_RUBRICS: "ADD_RUBRICS",
    DELETE_RUBRICS: "DELETE_RUBRICS",

    //GET INTENSITIES//
    GET_ALL_INTENSITIES: "GET_ALL_INTENSITIES",
    GET_REMEDY_COUNTS: "GET_REMEDY_COUNTS",
    GET_REMEDY_NAME: "GET_REMEDY_NAME",

    //GET ASTROINPUT//
    GET_ASTRO_INPUT: "GET_ASTRO_INPUT",
    SET_IDS: 'SET_IDS',
    SET_LIST: 'SET_LIST',
    SET_EXISTANCE: 'SET_EXISTANCE',
    GET_SUBSECTION: 'GET_SUBSECTION',

    //SHOW SIDENAVEBAR VALUES ON QUESTION TAB////
    SET_PARENT_OPTION: 'SET_PARENT_OPTION',
    SET_CHILD_OPTION: 'SET_CHILD_OPTION',
    SHOW_LAB_IMAGING: 'SHOW_LAB_IMAGING',
    SHOW_ADD_APPOINTMENT: 'SHOW_ADD_APPOINTMENT',


    HIDE_SHOW_SIDE_BAR:'HIDE_SHOW_SIDE_BAR'
}